# Generated by Django 3.2.16 on 2023-01-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytravelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=250)),
                ('member_img', models.ImageField(upload_to='pics')),
                ('member_details', models.TextField()),
            ],
        ),
    ]
